import {
  EvidenceItem,
  RiskLevel,
  ThreatVerdict,
  URLFeatureVector,
  RISK_THRESHOLDS
} from '@phishnetra/shared';

export interface RiskEvaluationResult {
  riskScore: number;
  riskLevel: RiskLevel;
  verdict: ThreatVerdict;
  confidence: number;
  evidence: EvidenceItem[];
}

export class RiskEngine {
  /**
   * Evaluates threat risk by synthesizing ML inference probability and heuristic rule signals.
   * @param mlProbability Probability generated by the ML baseline classifier [0.0 - 1.0]
   * @param mlConfidence Confidence measure [0.0 - 1.0]
   * @param features Deterministic URL feature vector
   */
  public evaluate(
    mlProbability: number,
    mlConfidence: number,
    features: URLFeatureVector
  ): RiskEvaluationResult {
    const evidence: EvidenceItem[] = [];
    let ruleScore = 0.0; // Rule score accumulation in range [0, 100]

    // 1. IP Address Hostname Rule
    if (features.has_ip_address === 1) {
      ruleScore += 35;
      evidence.push({
        featureKey: 'has_ip_address',
        featureValue: 'true',
        severity: 'HIGH',
        description: 'URL uses a raw IP address instead of a recognized domain name, a common phishing evasive tactic.',
        contribution: 0.35
      });
    }

    // 2. Suspicious Keywords Rule
    if (features.suspicious_keyword_count > 0) {
      const kwScore = Math.min(30, features.suspicious_keyword_count * 10);
      ruleScore += kwScore;
      evidence.push({
        featureKey: 'suspicious_keyword_count',
        featureValue: features.suspicious_keyword_count,
        severity: features.suspicious_keyword_count >= 2 ? 'HIGH' : 'MEDIUM',
        description: `URL contains ${features.suspicious_keyword_count} sensitive/credential keywords (e.g. login, verify, banking, secure).`,
        contribution: kwScore / 100
      });
    }

    // 3. Subdomain Depth Rule
    if (features.subdomain_count >= 3) {
      ruleScore += 20;
      evidence.push({
        featureKey: 'subdomain_count',
        featureValue: features.subdomain_count,
        severity: 'MEDIUM',
        description: `Excessive subdomain depth (${features.subdomain_count} levels) commonly indicates domain masquerading.`,
        contribution: 0.20
      });
    }

    // 4. Missing TLS / HTTPS Rule
    if (features.has_https === 0) {
      ruleScore += 15;
      evidence.push({
        featureKey: 'has_https',
        featureValue: 'false',
        severity: 'LOW',
        description: 'Unencrypted HTTP protocol detected. Sensitive communications are susceptible to interception.',
        contribution: 0.15
      });
    }

    // 5. TLD in Subdomain Masquerading
    if (features.tld_in_subdomain === 1) {
      ruleScore += 25;
      evidence.push({
        featureKey: 'tld_in_subdomain',
        featureValue: 'true',
        severity: 'HIGH',
        description: 'Top-level domain embedded in subdomains (e.g. paypal.com.attacker.xyz) indicates brand impersonation.',
        contribution: 0.25
      });
    }

    // 6. High Shannon Entropy Obfuscation
    if (features.entropy > 4.5) {
      ruleScore += 15;
      evidence.push({
        featureKey: 'entropy',
        featureValue: features.entropy,
        severity: 'MEDIUM',
        description: `High character entropy (${features.entropy}) indicates generated, randomized, or obfuscated URL paths.`,
        contribution: 0.15
      });
    }

    // 7. Excessive Hyphens in Hostname
    if (features.hyphen_count >= 3) {
      ruleScore += 15;
      evidence.push({
        featureKey: 'hyphen_count',
        featureValue: features.hyphen_count,
        severity: 'MEDIUM',
        description: `Multiple hyphens in domain (${features.hyphen_count}) frequently appear in typosquatting attempts.`,
        contribution: 0.15
      });
    }

    // 8. @ Symbol (URL userinfo trick)
    if (features.at_symbol_count > 0) {
      ruleScore += 30;
      evidence.push({
        featureKey: 'at_symbol_count',
        featureValue: features.at_symbol_count,
        severity: 'HIGH',
        description: 'URL contains "@" symbol, which can mislead browsers into ignoring preceding authentication credentials.',
        contribution: 0.30
      });
    }

    // ML Evidence Item
    const mlScore = mlProbability * 100;
    if (mlProbability >= 0.5) {
      evidence.push({
        featureKey: 'ml_phishing_classifier',
        featureValue: `${Math.round(mlProbability * 100)}%`,
        severity: mlProbability >= 0.8 ? 'CRITICAL' : 'HIGH',
        description: `Machine Learning baseline classifier evaluated URL feature vectors as high-risk phishing indicator (${Math.round(mlProbability * 100)}% probability).`,
        contribution: mlProbability * 0.6
      });
    } else {
      evidence.push({
        featureKey: 'ml_legitimate_classifier',
        featureValue: `${Math.round((1 - mlProbability) * 100)}%`,
        severity: 'INFO',
        description: `Machine Learning baseline classifier evaluated URL lexical patterns as standard legitimate traffic (${Math.round((1 - mlProbability) * 100)}% safe probability).`,
        contribution: 0.0
      });
    }

    // Composite Risk Calculation:
    // 60% Weight on ML Model Inference + 40% Weight on Deterministic Heuristic Evidence
    const normalizedRuleScore = Math.min(100, Math.max(0, ruleScore));
    const compositeScore = (mlScore * 0.60) + (normalizedRuleScore * 0.40);
    const finalRiskScore = Math.round(Math.min(100, Math.max(0, compositeScore)) * 10) / 10;

    // Determine Verdict and Risk Level from Configurable Thresholds
    let verdict: ThreatVerdict = 'SAFE';
    let riskLevel: RiskLevel = 'LOW';

    if (finalRiskScore > RISK_THRESHOLDS.HIGH_MAX) {
      verdict = 'PHISHING';
      riskLevel = 'CRITICAL';
    } else if (finalRiskScore > RISK_THRESHOLDS.SUSPICIOUS_MAX) {
      verdict = 'PHISHING';
      riskLevel = 'HIGH';
    } else if (finalRiskScore > RISK_THRESHOLDS.SAFE_MAX) {
      verdict = 'SUSPICIOUS';
      riskLevel = 'MEDIUM';
    } else {
      verdict = 'SAFE';
      riskLevel = 'LOW';
    }

    return {
      riskScore: finalRiskScore,
      riskLevel,
      verdict,
      confidence: mlConfidence,
      evidence
    };
  }
}

export const riskEngine = new RiskEngine();
