import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { useToast } from '../context/ToastContext';
import { ExecutiveThreatReport } from '@phishnetra/shared';
import {
  FileSpreadsheet,
  Download,
  RefreshCw,
  ShieldCheck,
  AlertTriangle,
  Zap,
  Clock,
  Target,
  Crosshair,
  TrendingUp,
  CheckCircle2,
  Copy,
  ExternalLink,
  Layers,
  ChevronRight,
  Sparkles
} from 'lucide-react';

export const ExecutiveBriefingPage: React.FC = () => {
  const { showToast } = useToast();
  const [report, setReport] = useState<ExecutiveThreatReport | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [timeRange, setTimeRange] = useState<string>('Last 30 Days');
  const [downloading, setDownloading] = useState<boolean>(false);
  const [showMarkdownModal, setShowMarkdownModal] = useState<boolean>(false);

  useEffect(() => {
    fetchReport();
  }, [timeRange]);

  const fetchReport = async () => {
    try {
      setLoading(true);
      const data = await api.getExecutiveReport(timeRange);
      setReport(data);
    } catch (err: any) {
      showToast('error', 'Failed to load executive report', err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadMarkdown = async () => {
    try {
      setDownloading(true);
      const token = localStorage.getItem('phishnetra_auth_token');
      const res = await fetch(`/api/reports/executive/download/markdown?timeRange=${encodeURIComponent(timeRange)}`, {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (!res.ok) throw new Error('Download failed');
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `PhishNetra_Executive_Dossier_${Date.now()}.md`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
      showToast('success', 'Dossier Exported', 'Executive Markdown dossier saved to downloads.');
    } catch (err: any) {
      showToast('error', 'Export Failed', err.message);
    } finally {
      setDownloading(false);
    }
  };

  const copyMarkdownToClipboard = () => {
    if (!report) return;
    const md = `# PhishNetra Executive Threat Intelligence Dossier
**Organization:** ${report.organizationName}
**Report ID:** ${report.reportId}
**Reporting Window:** ${report.timeRange}
**Generated:** ${new Date(report.generatedAt).toUTCString()}

---

## 1. Executive Summary & KPIs
- **Total Inbound Scans:** ${report.metrics.totalScans.toLocaleString()}
- **Phishing Attacks Neutralized:** ${report.metrics.phishingIntercepted.toLocaleString()}
- **Zero-Day Impersonation Campaigns:** ${report.metrics.zeroDayIdentified}
- **Mean Time to Neutralize (MTTN):** ${report.metrics.meanTimeToNeutralizeMinutes} minutes
- **Mitigation Success Rate:** ${report.metrics.mitigationSuccessRatePercent}%

---

## 2. Top Targeted Corporate Brands
${report.topTargetedBrands.map(b => `- **${b.brand}**: ${b.incidentCount} incidents (${b.riskPercentage}% attack volume)`).join('\n')}

---

## 3. Active Threat Campaigns & Adversary Attribution
${report.criticalCampaigns.map(c => `### ${c.campaignName}\n- **Origin / Attribution:** ${c.threatActorOrigin}\n- **IoC Signatures:** ${c.iocCount}\n- **Severity Level:** ${c.severity}\n`).join('\n')}

---

## 4. Strategic CISO & SOC Recommendations
${report.strategicRecommendations.map(r => `- [x] ${r}`).join('\n')}

_Confidential Threat Intelligence — Generated by PhishNetra Enterprise Platform_
`;
    navigator.clipboard.writeText(md);
    showToast('info', 'Copied to Clipboard', 'Executive Markdown dossier copied.');
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-6">
        <div>
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-gradient-to-tr from-cyan-500 to-indigo-600 rounded-xl shadow-lg shadow-cyan-500/20">
              <FileSpreadsheet className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white tracking-tight">Executive Threat Intelligence Dossier</h1>
              <p className="text-xs text-slate-400 font-mono">C-Suite security posture, brand targeting telemetry, adversary campaigns, and mitigation efficacy</p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {/* Time Range Selector */}
          <div className="flex items-center bg-slate-900 border border-slate-800 rounded-xl p-1">
            {['Last 7 Days', 'Last 30 Days', 'Last 90 Days'].map(tr => (
              <button
                key={tr}
                onClick={() => setTimeRange(tr)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${
                  timeRange === tr
                    ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/20'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                {tr}
              </button>
            ))}
          </div>

          <button
            onClick={() => fetchReport()}
            className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 hover:text-white hover:bg-slate-800 transition-colors"
            title="Refresh dossier"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>

          <button
            onClick={handleDownloadMarkdown}
            disabled={downloading}
            className="px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs shadow-lg shadow-cyan-500/20 flex items-center space-x-2 transition-all"
          >
            <Download className="w-4 h-4" />
            <span>{downloading ? 'Exporting...' : 'Export Dossier (.md)'}</span>
          </button>
        </div>
      </div>

      {report && (
        <div className="space-y-8 animate-in fade-in duration-300">
          {/* Metadata Sub-Header */}
          <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-2xl bg-slate-900/50 border border-slate-800/80 text-xs">
            <div className="flex items-center space-x-4">
              <span className="text-slate-400">Organization: <strong className="text-white">{report.organizationName}</strong></span>
              <span className="text-slate-600">|</span>
              <span className="text-slate-400 font-mono">Dossier ID: <strong className="text-cyan-400">{report.reportId}</strong></span>
              <span className="text-slate-600">|</span>
              <span className="text-slate-400">Window: <strong className="text-emerald-400">{report.timeRange}</strong></span>
            </div>
            <button
              onClick={() => copyMarkdownToClipboard()}
              className="text-xs text-slate-400 hover:text-cyan-400 flex items-center space-x-1.5 transition-colors font-mono"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Full Markdown</span>
            </button>
          </div>

          {/* Executive KPI Metric Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
            <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-5 space-y-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <Target className="w-12 h-12 text-cyan-400" />
              </div>
              <span className="text-[10px] font-mono uppercase text-slate-500">Inbound Scans</span>
              <h3 className="text-2xl font-black text-white">{report.metrics.totalScans.toLocaleString()}</h3>
              <p className="text-[11px] text-slate-400 flex items-center gap-1">
                <TrendingUp className="w-3 h-3 text-cyan-400" /> +14.2% from prior period
              </p>
            </div>

            <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-5 space-y-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <ShieldCheck className="w-12 h-12 text-rose-400" />
              </div>
              <span className="text-[10px] font-mono uppercase text-slate-500">Neutralized Attacks</span>
              <h3 className="text-2xl font-black text-rose-400">{report.metrics.phishingIntercepted.toLocaleString()}</h3>
              <p className="text-[11px] text-rose-400/80 font-mono">100% intercepted at gateway</p>
            </div>

            <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-5 space-y-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <Sparkles className="w-12 h-12 text-amber-400" />
              </div>
              <span className="text-[10px] font-mono uppercase text-slate-500">Zero-Day Attacks</span>
              <h3 className="text-2xl font-black text-amber-400">{report.metrics.zeroDayIdentified}</h3>
              <p className="text-[11px] text-amber-400/80 font-mono">Novel evasive signatures</p>
            </div>

            <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-5 space-y-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <Clock className="w-12 h-12 text-indigo-400" />
              </div>
              <span className="text-[10px] font-mono uppercase text-slate-500">Mean Time To Neutralize</span>
              <h3 className="text-2xl font-black text-indigo-400">{report.metrics.meanTimeToNeutralizeMinutes} <span className="text-sm font-normal text-slate-400">min</span></h3>
              <p className="text-[11px] text-indigo-300 font-mono">Autonomous sinkhole trigger</p>
            </div>

            <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-5 space-y-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <CheckCircle2 className="w-12 h-12 text-emerald-400" />
              </div>
              <span className="text-[10px] font-mono uppercase text-slate-500">Mitigation Efficacy</span>
              <h3 className="text-2xl font-black text-emerald-400">{report.metrics.mitigationSuccessRatePercent}%</h3>
              <p className="text-[11px] text-emerald-400/80 font-mono">Zero breach SLA achieved</p>
            </div>
          </div>

          {/* Section: Brands & Adversaries */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Top Targeted Brands */}
            <div className="lg:col-span-6 bg-slate-900/70 border border-slate-800 rounded-2xl p-6 space-y-5">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Target className="w-4 h-4 text-rose-400" />
                  <span>Targeted Brand Telemetry</span>
                </h3>
                <span className="text-[10px] font-mono text-slate-500">Share of attack volume</span>
              </div>

              <div className="space-y-4">
                {report.topTargetedBrands.map(b => (
                  <div key={b.brand} className="space-y-1.5">
                    <div className="flex justify-between text-xs font-semibold">
                      <span className="text-white">{b.brand}</span>
                      <span className="text-slate-400 font-mono">
                        {b.incidentCount} attacks ({b.riskPercentage}%)
                      </span>
                    </div>
                    <div className="w-full bg-slate-950 rounded-full h-2 overflow-hidden border border-slate-800/80">
                      <div
                        className="h-full bg-gradient-to-r from-cyan-500 to-rose-500 rounded-full transition-all duration-500"
                        style={{ width: `${b.riskPercentage}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Active Adversary Campaigns */}
            <div className="lg:col-span-6 bg-slate-900/70 border border-slate-800 rounded-2xl p-6 space-y-5">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Crosshair className="w-4 h-4 text-cyan-400" />
                  <span>Adversary Campaigns & Attribution</span>
                </h3>
                <span className="text-[10px] font-mono text-cyan-400 font-bold">Threat Cluster</span>
              </div>

              <div className="space-y-3">
                {report.criticalCampaigns.map(c => (
                  <div key={c.campaignName} className="p-4 rounded-xl bg-slate-950 border border-slate-800/80 flex items-center justify-between gap-3">
                    <div className="space-y-1">
                      <div className="flex items-center space-x-2">
                        <h4 className="text-xs font-bold text-white">{c.campaignName}</h4>
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-rose-500/20 text-rose-300 border border-rose-500/30">
                          {c.severity}
                        </span>
                      </div>
                      <p className="text-[11px] text-slate-400">Actor / Origin: <strong className="text-slate-300">{c.threatActorOrigin}</strong></p>
                    </div>
                    <div className="text-right">
                      <span className="text-xs font-bold text-cyan-400 font-mono">{c.iocCount}</span>
                      <div className="text-[10px] text-slate-500">Tracked IoCs</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Strategic Recommendations */}
          <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-6 space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-400" />
              <span>Strategic CISO & SOC Remediation Playbook</span>
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {report.strategicRecommendations.map((rec, i) => (
                <div key={i} className="p-3.5 rounded-xl bg-slate-950 border border-slate-800/80 flex items-start space-x-3 text-xs text-slate-300">
                  <CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                  <span className="leading-relaxed">{rec}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
